[package]
name = "sae"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
blake3 = "1.8.2"
rpassword = "7.4.0"
serde = { version = "1.0.228", features = ["derive"] }
serde-binary = "0.5.0"
users = "0.11.0"

[profile.release]
codegen-units = 1
